### ISSUE TITLE
Demo app doesn't work

### ISSUE THREAD

**Issue by ghost** [mikejarema/facebook-friend-rank#1]
The app located at http://facebook-friend-rank.herokuapp.com/demo/index.html doesn't work.  When i click the apply link, it doesn't do anything and a JavaScript error appears in the console complaining about accessToken of undefined.

**Comment by mikejarema** [comment]
I think FB updated their JS SDK as it pertains to access token retrieval.

Thanks for the report, I'll make the quick update to fix it.
On Jun 28, 2012 6:12 PM, "Blair Vanderhoof" <
reply@reply.github.com>
wrote:

**Comment by mikejarema** [comment]
Resolved now. Give the page a refresh and try again. Thanks for the bug report.

**Comment by ghost** [comment]
Confirmed.  Algorithm works pretty well too, thanks!

**Comment by mikejarema** [comment]
No prob. The algorithm as it stands is quite basic, however turned out to be more than enough for my needs.

This project is architected to be a solid framework within which to explore improvements to this basic approach. I've listed a couple of TODOs I'd like to tackle when I have the time and/or need that better take advantage of the parallel query capabilities that EventMachine brings to the table.

Let me know if you're interested in poking around further. The code could use more documentation, and I think any specific questions about "what does what?" and "where should such-and-such changes be made?" can help pinpoint where comments would provide the most value.
